# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/laman28/Projects/sb-lang

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/laman28/Projects/sb-lang

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laman28/Projects/sb-lang/CMakeFiles /home/laman28/Projects/sb-lang//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laman28/Projects/sb-lang/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laman28/Projects/sb-lang/CMakeFiles /home/laman28/Projects/sb-lang//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laman28/Projects/sb-lang/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sbl

# Build rule for target.
sbl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sbl
.PHONY : sbl

# fast build rule for target.
sbl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/build
.PHONY : sbl/fast

#=============================================================================
# Target rules for targets named test_bytecode

# Build rule for target.
test_bytecode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bytecode
.PHONY : test_bytecode

# fast build rule for target.
test_bytecode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/build
.PHONY : test_bytecode/fast

#=============================================================================
# Target rules for targets named test_vm

# Build rule for target.
test_vm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_vm
.PHONY : test_vm

# fast build rule for target.
test_vm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/build
.PHONY : test_vm/fast

#=============================================================================
# Target rules for targets named test_vm_module

# Build rule for target.
test_vm_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_vm_module
.PHONY : test_vm_module

# fast build rule for target.
test_vm_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/build
.PHONY : test_vm_module/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named test_simple_lib

# Build rule for target.
test_simple_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_simple_lib
.PHONY : test_simple_lib

# fast build rule for target.
test_simple_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/build
.PHONY : test_simple_lib/fast

builtin/base_functions.o: builtin/base_functions.c.o
.PHONY : builtin/base_functions.o

# target to build an object file
builtin/base_functions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/builtin/base_functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/builtin/base_functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/builtin/base_functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/builtin/base_functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/builtin/base_functions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/builtin/base_functions.c.o
.PHONY : builtin/base_functions.c.o

builtin/base_functions.i: builtin/base_functions.c.i
.PHONY : builtin/base_functions.i

# target to preprocess a source file
builtin/base_functions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/builtin/base_functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/builtin/base_functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/builtin/base_functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/builtin/base_functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/builtin/base_functions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/builtin/base_functions.c.i
.PHONY : builtin/base_functions.c.i

builtin/base_functions.s: builtin/base_functions.c.s
.PHONY : builtin/base_functions.s

# target to generate assembly for a file
builtin/base_functions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/builtin/base_functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/builtin/base_functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/builtin/base_functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/builtin/base_functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/builtin/base_functions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/builtin/base_functions.c.s
.PHONY : builtin/base_functions.c.s

bytecode/bytecode.o: bytecode/bytecode.c.o
.PHONY : bytecode/bytecode.o

# target to build an object file
bytecode/bytecode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/bytecode/bytecode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/bytecode/bytecode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/bytecode/bytecode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/bytecode/bytecode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/bytecode/bytecode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/bytecode/bytecode.c.o
.PHONY : bytecode/bytecode.c.o

bytecode/bytecode.i: bytecode/bytecode.c.i
.PHONY : bytecode/bytecode.i

# target to preprocess a source file
bytecode/bytecode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/bytecode/bytecode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/bytecode/bytecode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/bytecode/bytecode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/bytecode/bytecode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/bytecode/bytecode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/bytecode/bytecode.c.i
.PHONY : bytecode/bytecode.c.i

bytecode/bytecode.s: bytecode/bytecode.c.s
.PHONY : bytecode/bytecode.s

# target to generate assembly for a file
bytecode/bytecode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/bytecode/bytecode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/bytecode/bytecode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/bytecode/bytecode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/bytecode/bytecode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/bytecode/bytecode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/bytecode/bytecode.c.s
.PHONY : bytecode/bytecode.c.s

demo_math_lib.o: demo_math_lib.c.o
.PHONY : demo_math_lib.o

# target to build an object file
demo_math_lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/demo_math_lib.c.o
.PHONY : demo_math_lib.c.o

demo_math_lib.i: demo_math_lib.c.i
.PHONY : demo_math_lib.i

# target to preprocess a source file
demo_math_lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/demo_math_lib.c.i
.PHONY : demo_math_lib.c.i

demo_math_lib.s: demo_math_lib.c.s
.PHONY : demo_math_lib.s

# target to generate assembly for a file
demo_math_lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/demo_math_lib.c.s
.PHONY : demo_math_lib.c.s

dynarray/dynarray.o: dynarray/dynarray.c.o
.PHONY : dynarray/dynarray.o

# target to build an object file
dynarray/dynarray.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/dynarray/dynarray.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/dynarray/dynarray.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/dynarray/dynarray.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/dynarray/dynarray.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/dynarray/dynarray.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/dynarray/dynarray.c.o
.PHONY : dynarray/dynarray.c.o

dynarray/dynarray.i: dynarray/dynarray.c.i
.PHONY : dynarray/dynarray.i

# target to preprocess a source file
dynarray/dynarray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/dynarray/dynarray.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/dynarray/dynarray.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/dynarray/dynarray.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/dynarray/dynarray.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/dynarray/dynarray.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/dynarray/dynarray.c.i
.PHONY : dynarray/dynarray.c.i

dynarray/dynarray.s: dynarray/dynarray.c.s
.PHONY : dynarray/dynarray.s

# target to generate assembly for a file
dynarray/dynarray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/dynarray/dynarray.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/dynarray/dynarray.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/dynarray/dynarray.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/dynarray/dynarray.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/dynarray/dynarray.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/dynarray/dynarray.c.s
.PHONY : dynarray/dynarray.c.s

error/error.o: error/error.c.o
.PHONY : error/error.o

# target to build an object file
error/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/error/error.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/error/error.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/error/error.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/error/error.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/error/error.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/error/error.c.o
.PHONY : error/error.c.o

error/error.i: error/error.c.i
.PHONY : error/error.i

# target to preprocess a source file
error/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/error/error.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/error/error.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/error/error.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/error/error.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/error/error.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/error/error.c.i
.PHONY : error/error.c.i

error/error.s: error/error.c.s
.PHONY : error/error.s

# target to generate assembly for a file
error/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/error/error.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/error/error.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/error/error.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/error/error.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/error/error.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/error/error.c.s
.PHONY : error/error.c.s

lexer/lexer.o: lexer/lexer.c.o
.PHONY : lexer/lexer.o

# target to build an object file
lexer/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/lexer/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/lexer/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/lexer/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/lexer/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/lexer/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/lexer/lexer.c.o
.PHONY : lexer/lexer.c.o

lexer/lexer.i: lexer/lexer.c.i
.PHONY : lexer/lexer.i

# target to preprocess a source file
lexer/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/lexer/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/lexer/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/lexer/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/lexer/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/lexer/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/lexer/lexer.c.i
.PHONY : lexer/lexer.c.i

lexer/lexer.s: lexer/lexer.c.s
.PHONY : lexer/lexer.s

# target to generate assembly for a file
lexer/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/lexer/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/lexer/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/lexer/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/lexer/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/lexer/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/lexer/lexer.c.s
.PHONY : lexer/lexer.c.s

parser/parser.o: parser/parser.c.o
.PHONY : parser/parser.o

# target to build an object file
parser/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/parser/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/parser/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/parser/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/parser/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/parser/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/parser/parser.c.o
.PHONY : parser/parser.c.o

parser/parser.i: parser/parser.c.i
.PHONY : parser/parser.i

# target to preprocess a source file
parser/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/parser/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/parser/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/parser/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/parser/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/parser/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/parser/parser.c.i
.PHONY : parser/parser.c.i

parser/parser.s: parser/parser.c.s
.PHONY : parser/parser.s

# target to generate assembly for a file
parser/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/parser/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/parser/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/parser/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/parser/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/parser/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/parser/parser.c.s
.PHONY : parser/parser.c.s

sbl.o: sbl.c.o
.PHONY : sbl.o

# target to build an object file
sbl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/sbl.c.o
.PHONY : sbl.c.o

sbl.i: sbl.c.i
.PHONY : sbl.i

# target to preprocess a source file
sbl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/sbl.c.i
.PHONY : sbl.c.i

sbl.s: sbl.c.s
.PHONY : sbl.s

# target to generate assembly for a file
sbl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/sbl.c.s
.PHONY : sbl.c.s

test/test_bytecode.o: test/test_bytecode.c.o
.PHONY : test/test_bytecode.o

# target to build an object file
test/test_bytecode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/test/test_bytecode.c.o
.PHONY : test/test_bytecode.c.o

test/test_bytecode.i: test/test_bytecode.c.i
.PHONY : test/test_bytecode.i

# target to preprocess a source file
test/test_bytecode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/test/test_bytecode.c.i
.PHONY : test/test_bytecode.c.i

test/test_bytecode.s: test/test_bytecode.c.s
.PHONY : test/test_bytecode.s

# target to generate assembly for a file
test/test_bytecode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/test/test_bytecode.c.s
.PHONY : test/test_bytecode.c.s

test/test_simple_lib.o: test/test_simple_lib.c.o
.PHONY : test/test_simple_lib.o

# target to build an object file
test/test_simple_lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/test/test_simple_lib.c.o
.PHONY : test/test_simple_lib.c.o

test/test_simple_lib.i: test/test_simple_lib.c.i
.PHONY : test/test_simple_lib.i

# target to preprocess a source file
test/test_simple_lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/test/test_simple_lib.c.i
.PHONY : test/test_simple_lib.c.i

test/test_simple_lib.s: test/test_simple_lib.c.s
.PHONY : test/test_simple_lib.s

# target to generate assembly for a file
test/test_simple_lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/test/test_simple_lib.c.s
.PHONY : test/test_simple_lib.c.s

test/test_vm.o: test/test_vm.c.o
.PHONY : test/test_vm.o

# target to build an object file
test/test_vm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/test/test_vm.c.o
.PHONY : test/test_vm.c.o

test/test_vm.i: test/test_vm.c.i
.PHONY : test/test_vm.i

# target to preprocess a source file
test/test_vm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/test/test_vm.c.i
.PHONY : test/test_vm.c.i

test/test_vm.s: test/test_vm.c.s
.PHONY : test/test_vm.s

# target to generate assembly for a file
test/test_vm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/test/test_vm.c.s
.PHONY : test/test_vm.c.s

test/test_vm_module.o: test/test_vm_module.c.o
.PHONY : test/test_vm_module.o

# target to build an object file
test/test_vm_module.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/test/test_vm_module.c.o
.PHONY : test/test_vm_module.c.o

test/test_vm_module.i: test/test_vm_module.c.i
.PHONY : test/test_vm_module.i

# target to preprocess a source file
test/test_vm_module.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/test/test_vm_module.c.i
.PHONY : test/test_vm_module.c.i

test/test_vm_module.s: test/test_vm_module.c.s
.PHONY : test/test_vm_module.s

# target to generate assembly for a file
test/test_vm_module.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/test/test_vm_module.c.s
.PHONY : test/test_vm_module.c.s

vm/vm.o: vm/vm.c.o
.PHONY : vm/vm.o

# target to build an object file
vm/vm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/vm/vm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/vm/vm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/vm/vm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/vm/vm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/vm/vm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/vm/vm.c.o
.PHONY : vm/vm.c.o

vm/vm.i: vm/vm.c.i
.PHONY : vm/vm.i

# target to preprocess a source file
vm/vm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/vm/vm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/vm/vm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/vm/vm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/vm/vm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/vm/vm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/vm/vm.c.i
.PHONY : vm/vm.c.i

vm/vm.s: vm/vm.c.s
.PHONY : vm/vm.s

# target to generate assembly for a file
vm/vm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sbl.dir/build.make CMakeFiles/sbl.dir/vm/vm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytecode.dir/build.make CMakeFiles/test_bytecode.dir/vm/vm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm.dir/build.make CMakeFiles/test_vm.dir/vm/vm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vm_module.dir/build.make CMakeFiles/test_vm_module.dir/vm/vm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/vm/vm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple_lib.dir/build.make CMakeFiles/test_simple_lib.dir/vm/vm.c.s
.PHONY : vm/vm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... math"
	@echo "... sbl"
	@echo "... test_bytecode"
	@echo "... test_simple_lib"
	@echo "... test_vm"
	@echo "... test_vm_module"
	@echo "... builtin/base_functions.o"
	@echo "... builtin/base_functions.i"
	@echo "... builtin/base_functions.s"
	@echo "... bytecode/bytecode.o"
	@echo "... bytecode/bytecode.i"
	@echo "... bytecode/bytecode.s"
	@echo "... demo_math_lib.o"
	@echo "... demo_math_lib.i"
	@echo "... demo_math_lib.s"
	@echo "... dynarray/dynarray.o"
	@echo "... dynarray/dynarray.i"
	@echo "... dynarray/dynarray.s"
	@echo "... error/error.o"
	@echo "... error/error.i"
	@echo "... error/error.s"
	@echo "... lexer/lexer.o"
	@echo "... lexer/lexer.i"
	@echo "... lexer/lexer.s"
	@echo "... parser/parser.o"
	@echo "... parser/parser.i"
	@echo "... parser/parser.s"
	@echo "... sbl.o"
	@echo "... sbl.i"
	@echo "... sbl.s"
	@echo "... test/test_bytecode.o"
	@echo "... test/test_bytecode.i"
	@echo "... test/test_bytecode.s"
	@echo "... test/test_simple_lib.o"
	@echo "... test/test_simple_lib.i"
	@echo "... test/test_simple_lib.s"
	@echo "... test/test_vm.o"
	@echo "... test/test_vm.i"
	@echo "... test/test_vm.s"
	@echo "... test/test_vm_module.o"
	@echo "... test/test_vm_module.i"
	@echo "... test/test_vm_module.s"
	@echo "... vm/vm.o"
	@echo "... vm/vm.i"
	@echo "... vm/vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

